export const PLASTICITY_MCP_INSTRUCTIONS = `Use Plasticity MCP as the native CAD tool; keep the conversation in Codex. Prefer the named operation tools when they are available. If the needed operation is missing from the client's visible tool list, call plasticity_call with toolName="catalog" and a name or description query, read its input schema and validation note, then call plasticity_call with that operation's exact name and arguments. The server applies the original Zod schema and handler, including refinements the exported JSON Schema may not express; the dispatcher is not arbitrary code execution. Work in the explicitly selected Plasticity window and use millimeters and degrees. Before editing, read the current document, revision, bodies, and selection. Geometry and topology references are tied to that session, document, and revision; refresh them after every edit. Serialize edits. If a mutation times out or the connection drops, reconcile the scene before doing anything else: never retry the operation or undo it automatically.

For photos and sketches, treat observations as references, not exact dimensions. An unscaled image cannot establish millimeters. Use plasticity_analyze_design_reference, ask one compact, decision-relevant question package at a time, and do not ask again for details that cannot change the next design decision. For named products, search manufacturer CAD and dimensional sources, retain provenance and confidence, and distinguish exact native CAD from approximate mesh references. If Codex finds a selected CAD catalog page but does not expose direct file URLs, use plasticity_list_reference_assets with that page and the explicit allowed domains from the search; inspect its returned exact links before using a separate download/import operation. Do not invent or construct file URLs.

For exact face clearance, use plasticity_measure_parallel_planar_face_clearance for parallel planar faces with supported line, circle, and arc boundaries. For nonparallel faces, use plasticity_measure_nonparallel_planar_polygon_clearance when both trimmed faces have simple straight-edged loops; concave outlines, holes, and multiple loops are supported. Circular/curved edges and self-intersecting or touching loops remain unsupported. These measure the selected face pair, not whole-body clearance or collision; let unsupported topology fail explicitly.

Model functional parts directly in Plasticity and verify dimensions from native B-rep read-back. Keep strength checks proportional to risk: build a useful provisional enclosure, cover, stand, or bracket without requiring coupon campaigns or detailed FEA; do a practical load, mounting, clearance, wall, and printability review before calling it ready. Escalate to supported deterministic strength checks when the consequences, load, or a design decision warrant them, and state assumptions and unsupported claims plainly. Do not treat a mesh estimate or visual fit as exact evidence.

Workbench is optional; the user may inspect the model in Plasticity and continue in Codex. Use Workbench for review, validated dimension forms, tablet annotations, manufacturing profiles, and slicing when helpful. Slicing creates a ready job only. Show the exact model, printer, material, profile, orientation, and warnings, then wait for the user's explicit confirmation before calling any print-submission tool. Never start physical printing without that confirmation. Bambu Lab remains soon-only.`;
